CREATE DATABASE IF NOT EXISTS libraryDatabase;
USE libraryDatabase;

CREATE TABLE IF NOT EXISTS Admin (
    adminID VARCHAR(5) PRIMARY KEY,
    fName VARCHAR(50) NOT NULL,
    lName VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);
ALTER TABLE Admin AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS Staff (
    staffID VARCHAR(5) PRIMARY KEY,
    fName VARCHAR(50) NOT NULL,
    lName VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);
ALTER TABLE Staff AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS Member (
    memberID VARCHAR(5) PRIMARY KEY,
    fName VARCHAR(50) NOT NULL,
    lName VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);
ALTER TABLE Member AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS Login (
	email VARCHAR(100) NOT NULL PRIMARY KEY,
    password VARCHAR(255) NOT NULL
);
